### ISSUE TITLE
Usernames should be case insensitive

### ISSUE THREAD

**Issue by 4rnv** [JamesAC42/shovel#10]
Hello, it's me again, I really like the updated interface, especially on mobile.

# Steps to recreate issue

- Create account with a username say `yuki` and password `xxxxxxxx`.
- Try logging in by entering `Yuki`, `YUKI` or any case variation as username and `xxxxxxxx` as password.
- Incorrect username or password.

![Screenshot 2024-05-12 at 22-10-07 shovel](https://github.com/JamesAC42/shovel/assets/146211212/79ea40d5-6742-42de-9f21-912e7461ee7c)

![Screenshot 2024-05-12 at 22-10-52 shovel](https://github.com/JamesAC42/shovel/assets/146211212/094d0cd6-c1ff-41ce-9769-4d712b36f98e)

On most platforms usernames are case insensitive and the login is successful irrespective of whether the input is in CAPS or not. Right now it would be possible to create several accounts with the same username by using different variations of casing. Not sure if that is ideal.

**Comment by enisaras** [comment]
In my personal opinion usernames should always be emails to avoid this issue. Maybe we can have the user login with their email and treat display name separately.

**Comment by 4rnv** [comment]
> In my personal opinion usernames should always be emails to avoid this issue. Maybe we can have the user login with their email and treat display name separately.

Using email addresses would also help deal with forgotten passwords.

Alternately, usernames could be converted to lowercase before being stored, and during login the user input would also be converted to lowercase before comparison. Either approach would work IMO.

**Comment by JamesAC42** [comment]
Noted, will add (optional) email support and handle case-sensitivity better.
